#!/bin/sh
# shellcheck disable=SC1091
# shellcheck disable=SC2034

if [ "$1" = "restart" ] || [ "$1" = "stop" ] || [ "$1" = "kill" ]; then
	killall -q tailtaintdnsd
	killall -q tailtaintdns
fi

ENABLED=yes
PROCS=/jffs/addons/scmerlin.d/tailtaintdnsd
ARGS=""
PREARGS=""
PRECMD=""
POSTCMD=""
DESC=$PROCS
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /jffs/addons/scmerlin.d/sc.func
