#!/bin/sh
# shellcheck disable=SC2034
ln -s /jffs/addons/scmerlin.d/tailtopd /opt/bin 2>/dev/null
chmod 0755 /opt/bin/tailtopd

if [ "$1" = "stop" ] || [ "$1" = "kill" ]; then
	killall -q tailtopd
	killall -q tailtop
	rm -f /tmp/scmerlin-top*
fi

ENABLED=yes
PROCS=tailtopd
ARGS=""
PREARGS=""
PRECMD=""
POSTCMD=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
