#!/bin/sh
# shellcheck disable=SC2039
# shellcheck disable=SC3048
trap '' SIGHUP

tailfile="/tmp/syslog.log"

if [ "$(pidof syslog-ng | wc -w)" -gt 0 ]; then
	tailfile="/opt/var/log/messages"
fi

renice 15 $$
tail -F "$tailfile" | while read -r line; do
if echo "$line" | grep -q "Comm: dnsmasq Tainted:"; then logger "dnsmasq tainted detected, restarting dnsmasq"; service restart_dnsmasq; fi
if [ "$tailfile" = "/tmp/syslog.log" ] && [ "$(pidof syslog-ng | wc -w)" -gt 0 ]; then break; fi
done

renice 0 $$
