#!/bin/sh
# shellcheck disable=SC2039
trap '' SIGHUP
renice 15 $$
while true; do
	top -b -n 1 | tail -n +5 | head -n -1 | sed 's/S </S</g;s/S N/SN/g;s/S D/SD/g;s/R N/RN/g;' | \
awk -F" " -v OFS=',' '{if ($5 ~ /m[^\s\\]/){
printf "%s,%s,%s,%s,%s,%s,%s,", $1,$2,$3,$4,gensub(/m([^\s\\])/,"m,\\1","g",$5),$6,$7;for(i=8; i<=NF; ++i) printf "%s ", $i; print ""
}
else{
printf "%s,%s,%s,%s,%s,%s,%s,%s,", $1,$2,$3,$4,$5,$6,$7,$8;for(i=9; i<=NF; ++i) printf "%s ", $i; print ""
}
}' | \
sed 's/,$//g;s/S</S </g;s/SN/S N/g;s/SD/S D/g;s/RN/R N/g;' > /tmp/scmerlin-top
	sleep 4
done
renice 0 $$
