#!/bin/sh
# shellcheck disable=SC2039
trap '' SIGHUP

/jffs/addons/scmerlin.d/tailtop &

while true; do
	sleep 5
	if [ "$(pidof tailtop | wc -w)" -lt 1 ]; then
		logger -t scMerlin "tailtop dead, restarting..."
		killall -q tailtop
		sleep 5
		/jffs/addons/scmerlin.d/tailtop &
		logger -t scMerlin "tailtop restarted"
	fi
done
